blueprint:
  name: Stelle Ja/Nein Frage bei Auslöser
  description: |
    Diese Automation stellt eine Ja/Nein-Frage über einen Voice Assistant, 
    wenn ein Auslöser (z. B. Taster oder Geräteänderung) eintritt. 
    Die Antwort wird ausgewertet und entsprechende Aktionen ausgeführt.
  domain: automation
  author: Amon Reich
  homeassistant:
    min_version: 2025.6.99
  input:
    trigger_entity:
      name: Auslöser (Taste oder Gerät)
      description: Entität, die den Prozess startet (z. B. Taster, Schalter, Sensor)
      selector:
        entity: {}
    trigger_from:
      name: Von-Zustand (optional)
      description: Der vorherige Zustand, der einen Wechsel auslöst (leer lassen für beliebig)
      default: null
      selector:
        text: {}
    trigger_to:
      name: Nach-Zustand
      description: Der Zustand, der den Auslöser auslöst (z. B. 'on' oder 'pressed')
      selector:
        text: {}
    voice_assistant:
      name: Voice Assistant
      description: Der Sprachassistent, der die Frage stellt.
      selector:
        entity:
          filter:
            - domain: assist_satellite
    preannounce:
      name: Vorankündigung
      description: Spiele einen Ton vor der Frage ab.
      default: true
      selector:
        boolean: {}
    question:
      name: Frage
      description: Die gestellte Ja/Nein-Frage.
      selector:
        text: {}
    yes_actions:
      name: Aktionen bei „Ja“
      selector:
        action: {}
      default: []
    yes_answer:
      name: Antwort bei „Ja“
      default: Erledigt
      selector:
        text: {}
    no_actions:
      name: Aktionen bei „Nein“
      selector:
        action: {}
      default: []
    no_answer:
      name: Antwort bei „Nein“
      default: Nichts wird unternommen
      selector:
        text: {}
    other_actions:
      name: Aktionen bei Unklar
      selector:
        action: {}
      default: []
    other_answer:
      name: Antwort bei Unklar
      default: Wie bitte? Das habe ich nicht verstanden. Bitte noch einmal wiederholen.
      selector:
        text: {}
    number_of_retries:
      name: Wiederholungen bei Unklarheit
      default: 0
      selector:
        number:
          min: 0
          max: 10
          step: 1
          mode: slider

trigger:
  - platform: state
    entity_id: !input trigger_entity
    from: !input trigger_from
    to: !input trigger_to

variables:
  number_of_retries: !input number_of_retries

action:
  - repeat:
      sequence:
        - service: assist_satellite.ask_question
          data:
            entity_id: !input voice_assistant
            question: !input question
            preannounce: !input preannounce
            answers:
              - id: 'yes'
                sentences: # ['Ja']
                - 'Ja'
                - Sicher
                - Absolut
                - Mach weiter
                - Bitte tu es
                - Natürlich
                - Das ist in Ordnung
                - Mach es
                - Jep
                - Ja
                - Ok
                - Okay
                - Bestätigt
                - Ich stimme zu
                - Klingt gut
                - Du hast es
                - Definitiv
                - Auf jeden Fall
                - Warum nicht
                - In der Tat
                - Bestätigt
                - Lass es uns machen
                - Sicherlich
                - Richtig
                - Gut
                - Alles gut
                - Mach es so
                - Ich genehmige
                - Das stimmt
                - Ich bin damit einverstanden
                - Kein Problem
                - Leg los
                - Klingt gut
                - Ich bin dabei
                - Fortfahren
                - Es ist ein Ja
                - Ich bin dabei
                - Okay ja
                - Das ist ein Ja
                - Ja mach weiter
                - Ich bin damit einverstanden
                - Positiv
                - Mach das
                - Es ist okay
                - Funktioniert für mich
                - Ich bin damit einverstanden
                - Jep mach es
                - Bitte mach weiter
                - Das will ich
              - id: 'no'
                sentences: # ['Nein']
                - 'Nein'
                - Später vielleicht
                - Nö
                - Tu es nicht
                - Bitte nicht
                - Nein danke
                - Ich glaube nicht
                - Nicht jetzt
                - Das ist ein Nein
                - Ich würde lieber nicht
                - Auf keinen Fall
                - Nicht wirklich
                - Abbrechen
                - Negativ
                - Stopp
                - Tu es nicht
                - Ich habe Nein gesagt
                - Nicht nötig
                - Egal
                - Nicht notwendig
                - Nein das stimmt nicht
                - Ich stimme nicht zu
                - Überspringe es
                - Nicht fortfahren
                - Das will ich nicht
                - Mach nicht weiter
                - Lass es
                - Das ist falsch
                - Ich ziehe es vor nicht
                - Nein danke
                - Ich bin nicht einverstanden
                - Ich sage Nein
                - Lass es uns nicht tun
                - Nicht dieses Mal
                - Ich bin nicht dabei
                - Bitte tu das nicht
                - Keine Aktion durchführen
                - Ich würde Nein sagen
                - Keine Aktion nötig
                - Ich bin dagegen
                - Ich würde es überspringen
                - Lieber nicht
                - Nicht heute
                - Ich bin mir nicht sicher besser nicht
                - Das will ich nicht
                - Das wird nicht nötig sein
                - Ich stimme nicht zu
                - Nein das ist falsch
                - Lass es uns überspringen
                - Ich fühle mich dabei nicht wohl
      response_variable: response
    - choose:
      - conditions:
        - condition: template
          value_template: '{{response.id == ''yes''}}'
        sequence:
        - sequence: !input yes_actions
        - action: assist_satellite.announce
          metadata: {}
          data:
            message: !input yes_answer
            preannounce: false
          target:
            entity_id: '{{voice_assistant}}'
      - conditions:
        - condition: template
          value_template: '{{response.id == ''no''}}'
        sequence:
        - sequence: !input no_actions
        - action: assist_satellite.announce
          metadata: {}
          data:
            message: !input no_answer
            preannounce: false
          target:
            entity_id: '{{voice_assistant}}'
      default:
      - sequence: !input other_actions
      - action: assist_satellite.announce
        metadata: {}
        data:
          message: !input other_answer
          preannounce: false
        target:
          entity_id: '{{voice_assistant}}'
    until:
    - condition: template
      value_template: '{{ (response is defined and response.id in [''yes'',''no''])
        or repeat.index > number_of_retries}}'
          response_variable: response
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ response.id == 'yes' }}"
              sequence:
                - choose: []
                  default: !input yes_actions
                - service: assist_satellite.announce
                  data:
                    entity_id: !input voice_assistant
                    message: !input yes_answer
                    preannounce: false
            - conditions:
                - condition: template
                  value_template: "{{ response.id == 'no' }}"
              sequence:
                - choose: []
                  default: !input no_actions
                - service: assist_satellite.announce
                  data:
                    entity_id: !input voice_assistant
                    message: !input no_answer
                    preannounce: false
          default:
            - choose: []
              default: !input other_actions
            - service: assist_satellite.announce
              data:
                entity_id: !input voice_assistant
                message: !input other_answer
                preannounce: false
      until:
        - condition: template
          value_template: >
            {{ (response is defined and response.id in ['yes','no']) or repeat.index > number_of_retries }}
